version: 2
jobs:
  build:
    docker:
      - image: circleci/node:12.11

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}
            - v1-dependencies-

      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test
      - run: git config --global -l
      - run: git config --global user.email rafael.audy@gmail.com
      - run: git config --global user.name rafaelaudy
      - run: cd web && yarn deploy
