version: 2.0
jobs:
  build:
    branches:
      only:
        - master

    docker:
      - image: cypress/base:8
        environment:
          TERM: xterm

    working_directory: ~/repo

    parallelism: 1

    steps:
      - checkout

      - restore_cache:
          paths:
            - /root/.cache/Cypress/

          keys:
            - v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn install

      - save_cache:
          paths:
            - /root/.cache/Cypress/
            - node_modules
          key: v1-dependencies-{{ checksum "yarn.lock" }}

      - run: yarn test:ci

      - add_ssh_keys:
          fingerprints:
            - "8c:7a:17:fe:7e:ca:86:53:e0:a3:f6:ec:0d:c2:8e:03"

      - run: git config --global -l
      - run: git config --global user.email rafael.audy@gmail.com
      - run: git config --global user.name rafaelaudy
      - run: yarn deploy
